version: '3'

services:

  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    volumes:
      - /app/node_modules
      - ./backend:/backend
    ports:
      - "4000:4000"
    image: rupaf
    expose:
      - "4000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
  
  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    image: rupab
    expose:
      - "3000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
      
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"